config/routes.rb
Rails.application.routes.draw do
 #以下はnew(新規作成)のルーティング設定
 # get 'lists/new'
 # post 'lists' => 'lists#create' #データを追加するためのルーティングをここで設定

 #以下はindex(データ一覧)のルーティング設定
 # get 'lists' => 'lists#index'

 #以下はshow(データの詳細)のルーティング設定
 # get 'lists/:id' => 'lists#show',as: 'list'
 #どの投稿データを表示するかを判別するために、投稿データのidもURLに含めます。
 #as:オプションを追加することで、「'lists#show'の設定を、listとして利用できる」


 #以下はedit(データを編集するフォーム)のルーティング設定
 # get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'

  #以下はupdate(データを更新するフォーム)のルーティング設定
  # patch 'lists/:id' => 'lists#update', as: 'update_list'
  #更新の場合はPATCHで指定します

  #以下はdestroy(データを削除するフォーム)のルーティング設定
  # delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'

  #以下はホーム画に戻るルーティング設定
  get '/top' => 'homes#top' #URLに「/top」を追加することでホーム画面に戻るルーティング設定

  resources :lists#ルーティングを自動作成

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image #Listモデルにtitleとbodyに加えて画像を扱うためのimageカラムが追記された

  validates :title, presence: true #「必須入力」の設定
  validates :body, presence: true #「必須入力」の設定
  validates :image, presence: true #「必須入力」の設定
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new #データの新規作成フォームを表示するアクション

    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @list = List.new #@list=インスタンス変数 List.new=空のモデル
  end

  def create #投稿を保存するためのcreateアクションを作成
    @list = List.new(list_params) # フォームに記述した文字やデータを受け取る＆受け取ったデータを元にインスタンスを作成する
     if @list.save # インスタンスにsaveメソッドを使いデータベースに保存する
      redirect_to list_path(@list.id)
    else
      #@lists = List.all #何も入力せず更新ボタンを押した場合、一覧ページに飛ぶ（そのための定義文）
      render :new #※ render :アクション名で、同じコントローラ内の別アクションのViewを表示できます
    end
        #redirect_to list_path(list.id) # トップ画面へリダイレクト
  end

  def index #一覧表示のためのアクション
    @lists = List.all #@lists=インスタンス変数
    #(あらかじめControllerのアクションでインスタンス変数を指定しておくことで、viewファイル上でインスタンス変数に格納された情報を表示させることができます。)
    #List.allとは・・・listsテーブルに保存されている全てのデータを取得することができます。
  end

  def show
    @list = List.find(params[:id]) #アクション内にparams[:id]と記述することで、詳細画面で呼び出される投稿データを URLの/lists/:id 内の:idで判別可能にする。
    #今回はレコードを1件だけ取得するので、インスタンス変数名は単数形の「@list」にします。
  end

  def edit #編集機能のためのアクション
    @list = List.find(params[:id]) #今回は投稿済みのデータ(保存されているデータ)を編集するので、findメソッドを用いて、データを取得します。
  end
  def update #更新機能のためのアクション
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id) #データの更新後に更新結果を詳細画面(show)に表示するためにshowアクションにリダイレクトさせます
  end

  def destroy #削除機能のためのアクション
    list = List.find(params[:id])  # データ（レコード）を1件取得
    list.destroy  # データ（レコード）を削除
    redirect_to '/lists'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ(改竄データを送信した場合も、そのデータは保存される→脆弱性を防ぐ仕組みのこと)
  def list_params #list_params内では、保存したいデータの絞り込みが行われています。
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>

    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>
      </ul>
    </nav>
    <main>

    <%= yield %>

  　</main>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>
<!--RouteingにはupdateのためにHTTPメソッドをPATCH,名前付きルートをupdate_listに設定しているので-->

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
<% @lists.each do |list| %>
<!--@listsの中身は、コントローラ(lists_controller.rb)で代入した内容がそのまま入っています。-->
<!--eachメソッドは、配列やハッシュがもつ要素を順番に取得して処理を実行したい時に使用しました。今回はListレコードの数だけ繰り返し処理を行います-->
<!--each文に「＝」を付けた場合、@listsそのものが出力されてしまう-->
  <div class="list-box">
    <% if list.image.attached? %><!--「.attached?」はimageが存在するかを確認するメソッド-->
      <%= image_tag list.image, size: "200x200" %><!--listに紐ついているimageをimage_tagに渡すことで画像を表示することができます。-->
      <!--オプションとしてsizeを指定することで画像サイズを変更することができる-->
    <% else %>
      <%= image_tag 'no_image', size: "200x200" %><!--画像が保存されていない場合、no_imageが表示される-->
    <% end %>
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span><!--「list.body」はListモデルのbodyカラムに入っているデータを呼び出している記述-->
      <span class="list-title"><%=link_to list.title, list_path(list.id) %></span><!--リンク先URLは、/lists/:idの「:idに該当する部分」を指定します。-->
      <!--「SPAN」とは、単体では特に意味を持たないタグですが、<span>～</span>で囲った部分をインライン要素としてグループ化することができるタグです。-->
      <!--各レコードの内容は、listという変数に格納されます。ここでは、list.titleと記述することで、投稿のタイトルが表示されます。-->
    </div>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %><!--errorsは、any? と組み合わせることで、エラーが発生しているかどうかを判定できます。-->
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %><!--errorsは、full_messagesと組み合わせることで、エラーの内容を出力できます。-->
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!-- form_with部分 --><!--簡単にフォームを生成することができるヘルパー-->
<%= form_with model: @list,url:lists_path,method: :post do |f| %><!--フォームからデータを送信した後にデータベースへ保存する必要がある-->
<!--@listの中身は、コントローラ(lists_controller.rb)で代入した内容がそのまま入っています。-->

  <h4>タイトル</h4>
  <%= f.text_field :title %><!--タイトルを入力する部分を作成-->

  <h4>本文</h4>
  <%= f.text_area :body %><!--本文の部分の記述-->

  <h4>画像</h4><!-- 画像検索機能を追加 -->
  <%= f.file_field :image, accept: "image/*" %>
  <!--accept: "image/*"を使い、画像ファイルしか投稿できないようする-->

  <%= f.submit '投稿' %><!--投稿の部分の記述-->
<% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2><!--タイトル入力枠の作成-->
<p><%= @list.title %></p>

<h2>本文</h2><!--本文入力枠の作成-->
<p><%= @list.body %></p>

<h2>画像</h2><!--画像入力枠の作成-->
<% if @list.image.attached? %>
  <%= image_tag @list.image, size: "300x300" %>
<% else %>
  <%= image_tag 'no_image', size: "300x300" %>
<% end %>

<!--編集画面へ遷移するリンクを設定-->
<%= link_to "編集", edit_list_path(@list.id) %>
<!--削除画面へ遷移するリンクを設定-->
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<!--data-confirmを用いて確認ダイアログも表示されるように設定-->